server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8085

  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=api/users/**

          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
              - Path=api/ratings/**

          - id: HOTEL-SERVICE
            uri: lb://HOTEL-SERVICE
            predicates:
              - Path=api/hotels/**

#Okta Configuration
okta:
  oauth2:
    issuer: https://dev-98412062.okta.com/oauth2/default
    audience: api://default
    client-id: 0oagg6i6buFujGpbx5d7
    client-secret: EK1KhW2NYaWbYwmJHTgLn4jRb4vrd6WyoIILcweFQb-tqsIU_z7gaKgQ96M2CT_m
    scopes: openid, profile, email, offline_access



#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka